{% set version = "0.9.9" %}

package:
  name: numpy_groupies
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/numpy_groupies/numpy_groupies-{{ version }}.tar.gz
  sha256: ae98a51ddfe79950c5e7c4f308971c3345b84902a18c24b119d81ca86b0d8412

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    # This is a bogus build dependency and should be fixed usptream,
    - pytest-runner
  run:
    - python

test:
  imports:
    - numpy_groupies

about:
  home: https://github.com/ml31415/numpy-groupies
  license: BSD 2-Clause
  # Not in the soure tarball.
  # license_file: LICENSE.txt
  summary: 'Optimised tools for group-indexing operations: aggregated sum and more.'

extra:
  recipe-maintainers:
    - ocefpaf
