{% set name = "numpy_groupies" %}
{% set version = "0.11.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b0e9cf7a4d015beca969f1e90463fa90972df8380a722eb96d679f8838d2f6fe

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - numpy

test:
  imports:
    - numpy_groupies
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ml31415/numpy-groupies
  license: BSD-2-Clause
  license_file: LICENSE.txt
  summary: 'Optimised tools for group-indexing operations: aggregated sum and more.'

extra:
  recipe-maintainers:
    - dcherian
    - ocefpaf
    - synapticarbors
    - ml31415
