{% set version = "0.9.7" %}

package:
  name: numpy_groupies
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/numpy_groupies/numpy_groupies-{{ version }}.tar.gz
  sha256: be88c76cfb485104f629c31c9aaee552c35cb1e179a986c56e2aacb564f1f2ed

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    # This is a bogus build dependency and should be fixed usptream,
    - pytest-runner
  run:
    - python

test:
  imports:
    - numpy_groupies

about:
  home: https://github.com/ml31415/numpy-groupies
  license: BSD 2-Clause
  # Not in the soure tarball.
  # license_file: LICENSE.txt
  summary: 'Optimised tools for group-indexing operations: aggregated sum and more.'

extra:
  recipe-maintainers:
    - ocefpaf
