{% set name = "numpy_groupies" %}
{% set version = "0.10.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: f0aa57d81ae99c70f0a8b4f1ca53447951ecff63d6ca4edb0906206229044e2d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - numpy

test:
  imports:
    - numpy_groupies
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ml31415/numpy-groupies
  license: BSD-2-Clause
  license_file: LICENSE.txt
  summary: 'Optimised tools for group-indexing operations: aggregated sum and more.'

extra:
  recipe-maintainers:
    - dcherian
    - ocefpaf
    - synapticarbors
    - ml31415
