{% set version = "0.9.14" %}

package:
  name: numpy_groupies
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/numpy_groupies/numpy_groupies-{{ version }}.tar.gz
  sha256: 01b7aeca60e643db34875c9823ea6775742adafe5bb406bca14367743ef81800

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python

test:
  imports:
    - numpy_groupies

about:
  home: https://github.com/ml31415/numpy-groupies
  license: BSD-2-Clause
  license_file: LICENSE.txt
  summary: 'Optimised tools for group-indexing operations: aggregated sum and more.'

extra:
  recipe-maintainers:
    - ocefpaf
    - synapticarbors
