travis:
  secure:
    BINSTAR_TOKEN: acmx+Y4h4GgorDx4YClbECv0PYek/ppib7yTfPUMk2/7srKMWmhtTqfXkzb3NRBpZx3XsR8IspMqOypygwqVTBelNDIBfThjz1zqjaS2u+bJcLejXkzt2d4KeUZDkA76KIC0i32MZXev/BhSFUqSAcEMtWTFCN2DLA/hP3lBgK9qEdWU9s7s3hGmbucuG+OXwEMvt1D9w1119ghv0eMZRiC2ux4jdNcR/XRrWh/XnOls9xJa1P6zicQL2S++aKFSNAVJisjB4hQlFfU9FcYJX430WoN6idSfhL1WZmDmdRRl0BmXs+plZLXE0c2T5j5g6Tu8MHYTnCZlIaHg4H+yZp5b2RMbcM3aLhxmhh71V6GUCEz00d3aN1RhX+3IAzny53zi/AgGhe6ogQBC7C+SaFYkYGUXBYXzoQKnTMOdnoOjpulX7MfZTAm9U2IUsZyaPkO1hX2UToW+1mEcSJtU8G4FRNLLwbYLFI5gZ2lmJKw1Oc67v177k7YWatrT7fKXi0X+DTNhyXTl/W9EsdLjMSOTU8/D+N/TGt10iFj/vYUxvQhruUp9d5Fu/8BYcZifZm3z5UxdISEcWcL5VamOvJB/LQLrPbMOyL0sRxPapA8wF8xKiVGoFAGK3ka9EMwPUyFxvHKPEgv98eFAXrMeZfA+/ZmUCkVsT8XKCeUPkS8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
