travis:
  secure:
    BINSTAR_TOKEN: hky+SUo1Ef00RnNVGDr5wFe/HYMGl5kDPt8bBNp9Tiag0jzcAUqSgOxivka9mcH0VE3lJ/sCOQMDPT4Ky2EbtLgFBqAiCUM1Ve7X0GBfFwetuO+Pqb+IZCxQuQ0oAQKuATiN0ouh5mvnP1ZA0RKTc9BAbXadj/o4yVOYqCZphbGDbtvU2s3siiu/2rcH/sWTQy9HOVl1a3Y7dSGo1IFQIUaKgN8cWYmhPtBI9Q/EguDc5nqm6SHlt7O0nCT3hK4iiALuP55a98R7EwIJGx0s9OCuaoVTirLqn/2KkDv0Z6xU7ZUNyP73lTGegcfZDfgU8AJ8gUrXl/qh677kzyEKRKEEX01by8O+iKBu2gysfdnNCs1JGi4V2C1r+5MA7hLqrK5pM3u087KaAPxpeTvNFZCzSjXfspaBSvP9Uw0YcV0YAIjFmIzCtEYQBdcjSgfekAnS29A9uxVj86BzGqx1myRar56/u/undQ79riFsW3yAqSEpCmIRThJN+7HOuvW9V+CAIHLr99jk3g1IcIRI8Kp8Yc/WpQfkcTH3UkGjw89EQ4qArL+JNCu2qxeDRs3SUIY42dyWUnMagQkZOEt26m0urfNkglsHkvFjIk5g8AXejUmL64Y5YppdRz3fRAPydR0ZBr+3MQL8P+NdeI5lSDs2mCrOn1MH0wq2bIQw+1M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
