travis:
  secure:
    BINSTAR_TOKEN: hKKV9sPuef4Bk7kizN4CvjJQcMvA5ecRuY4PMiG/+e7R1i1aihTGU9eovzjXSOD0lclv42wZtii25Kcj9AWvIQ1mnf3rWZpAucFJU9zMotsQrmvh4rn9Yvs3Vl61JSctDFCdp2BELJ7L6T4FNvCXbb9VPX4NaTZHiME0X9Tq6ylbyWJR7rKpB7U44Q9Bng3zjDYbfqbAhy7fATggp3UGf0tDAnX1PrhC+3V8hgprt53mJmtIWK2FY+b3ZkOYUndSOekUGod003t021fSlMLviqnxJtuWG3Kjel3o7IAgT2roSrbirCtpV9nENLIMTCgbdD66v3dn01nkNOdpiE5rov4T6b/5YW7GwtXhpEpzq+kZhXINBJW2xhbzLnMrEFytQS3dnMUxjsPYzwY+Q75oiE1GSxFe7CJRhmM/AuWcRXp8fKEMUEgjOSevWf0z1Q1uQHtHTavuGb9/jLJWkorJfWDh5kk0G63Zsih6r2JsYZrsjZXmBzD36Rb9pzpyaTpdXexG0O0Ue0gReQWCHfGvqYbDrTY5n5Q+voWGmiOqfMTwQxM5ijKlA5DqAr59gDlp9MDiWFVaS3SwF3Tp6+tuNOfQdjI/pzTf8b2C6W9k+DcDWl1s54me5WvlCJlFaMxqoQZhtDVBh4ywIlzkG9E50nPZ+J10PHdNwzitDjxu/pk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
