travis:
  secure:
    BINSTAR_TOKEN: kOcBskIaMvk+qXHkn/tO+mUA4bHGhi7LBFBzIdM13aOZT38d61A2HIw9GAxKplTymaw5cKv0dLtNCcreayJ8zmChgr/mV1W0DNY/3YFL4kwzHmYNHZY+R9/9iHkoZOgi+Tz/i5GWUBjWZidiknCeQPthvFwPSdHc8pvPUlipXuKXZ4OAGNvuyM3I5r5xlF8UvovBHcvUvznaOibyVBedXt6whhCmlFc8DlPVMN+dzkumy+lhtbkXrFGyyir1HCK7RRTjbrlFTyxD+EoO81uTIiV8ibitVObw879guYr+JDvhqSK/cuncnztWAU82RQwQRyuOG/j0wC+++bbC5lCypX8fKgf2UukFeXIzXhkLdSxK7xTMtCJ6o/yC3vQ504K2R1QoGpzD/vEh5OqBEzV0zXDKiN0AYh2IN/XdFdxdsDcK4cSwg7c89KUuepzE53haAnFXLVcJ54gbgKEuuvVbzwCtgiIUQnJ7uEy4DuXIoa8iaeYpHNZ3v5/Lph946eHx7doZjqn5KTCG5XgRgPnJtLZHhkV0okE2VPU+QK9Krynmg0iEUufkJyYsSkVLYGvzvBx5+16lnkhV+RkB/EP50Y6e7E2TxmJ1EfnjoEuhEJr2OAuE3JegLOuzXhJIE/dHDwbHNBVkssaUhQO6LW8Vsdgy/T6SpyoYMdzyxUFIBuE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
